import global_climate_action from './data/global_climate_action.json'
import host_country_guests from './data/host_country_guests.json'
import intergovernmental_orgs from './data/intergovernmental_orgs.json'
import media from './data/media.json'
import non_governmental_orgs from './data/non_governmental_orgs.json'
import party_overflow from './data/party_overflow.json'
import special_agencies_and_rel_orgs from './data/special_agencies_and_rel_org.json'
import special_agencies_and_rel_orgs_overflow from './data/special_agencies_and_rel_org_overflow.json'
import temp_passes from './data/temp_passes.json'
import un_secretariat_units_bodies from './data/un_secretariat_units_bodies.json'
import un_secretariat_units_bodies_overflow from './data/un_secretariat_units_bodies_overflow.json'
import parties from './data/parties.json'
import conference_invitees from './data/conference_invitees.json'

export const keys = [
  'parties',
  'global_climate_action',
  'host_country_guests',
  'intergovernmental_orgs',
  'media',
  'non_governmental_orgs',
  'party_overflow',
  'special_agencies_and_rel_orgs',
  'special_agencies_and_rel_orgs_overflow',
  'temp_passes',
  'un_secretariat_units_bodies',
  'un_secretariat_units_bodies_overflow',
  'conference_invitees'
]

export const Datasets = {
  parties: parties,
  global_climate_action: global_climate_action,
  host_country_guests: host_country_guests,
  intergovernmental_orgs: intergovernmental_orgs,
  media: media,
  non_governmental_orgs: non_governmental_orgs,
  party_overflow: party_overflow,
  special_agencies_and_rel_orgs: special_agencies_and_rel_orgs,
  special_agencies_and_rel_orgs_overflow: special_agencies_and_rel_orgs_overflow,
  temp_passes: temp_passes,
  un_secretariat_units_bodies: un_secretariat_units_bodies,
  un_secretariat_units_bodies_overflow: un_secretariat_units_bodies_overflow,
  conference_invitees: conference_invitees
}

export const relationOptions = [
  'Paid relationship/contract with the nominating entity',
  'Paid relationship/contract with an affiliate/member of the nominating entity',
  'Unpaid advisory capacity',
  'Partner/sponsorship of the nominating entity',
  'Guest of the nominating entity',
  'Other (please specify)',
  'Choose not to disclose'
]

export const nominatorOptions = [
  'Albania',
  'Algeria',
  'Andorra',
  'Angola',
  'Antigua and Barbuda',
  'Argentina',
  'Armenia',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bhutan',
  'Bolivia (Plurinational State of)',
  'Bosnia and Herzegovina',
  'Botswana',
  'Brazil',
  'Brunei Darussalam',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cabo Verde',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Central African Republic',
  'Chad',
  'Chile',
  'China',
  'Colombia',
  'Comoros',
  'Congo',
  'Cook Islands',
  'Costa Rica',
  "Côte d'Ivoire",
  'Croatia',
  'Cuba',
  'Cyprus',
  'Czechia',
  "Democratic People's Republic of Korea",
  'Democratic Republic of the Congo',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Eswatini',
  'Ethiopia',
  'European Union',
  'Fiji',
  'Finland',
  'France',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Greece',
  'Grenada',
  'Guatemala',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Holy See',
  'Honduras',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran (Islamic Republic of)',
  'Iraq',
  'Ireland',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  'Kuwait',
  'Kyrgyzstan',
  "Lao People's Democratic Republic",
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands',
  'Mauritania',
  'Mauritius',
  'Mexico',
  'Micronesia (Federated States of)',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Morocco',
  'Mozambique',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands (Kingdom of the)',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'Niue',
  'North Macedonia',
  'Norway',
  'Oman',
  'Pakistan',
  'Palau',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Poland',
  'Portugal',
  'Qatar',
  'Republic of Korea',
  'Republic of Moldova',
  'Romania',
  'Russian Federation',
  'Rwanda',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Vincent and the Grenadines',
  'Samoa',
  'Sao Tome and Principe',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'South Sudan',
  'Spain',
  'Sri Lanka',
  'State of Palestine',
  'Sudan',
  'Suriname',
  'Sweden',
  'Switzerland',
  'Syrian Arab Republic',
  'Tajikistan',
  'Thailand',
  'Timor-Leste',
  'Togo',
  'Tonga',
  'Trinidad and Tobago',
  'Tunisia',
  'Türkiye',
  'Turkmenistan',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom of Great Britain and Northern Ireland',
  'United Republic of Tanzania',
  'United States of America',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Venezuela (Bolivarian Republic of)',
  'Viet Nam',
  'Yemen',
  'Zambia',
  'Zimbabwe'
]

export const nominatorInstructions =
  'The nominator dropdown only includes countries. If you are looking for a non-country nominator – please enter the term in the search box below.'

export const relationInstructions =
  'The categories in the "Relation to Nominator" dropdown are the choices available to the nominator when the delegate is nominated. There are no additional descriptions of the categories.'

export const searchBoxInstructions =
  'Search Box – please enter a search term which will be conducted across Title, Department, Organization, Nominator and Name.'

export const searchBoxNote =
  'The search function is not an exact word match. It uses approximation to avoid missing values due to typos or alternative spellings.'

export const searchInstructions =
  'This data comes from the COP 29 UNFCCC Final List of Participants – on site delegates-excel file. The excel file separates delegate by badge category and draws its data from what is submitted when a delegate is nominated and confirmed.'
